<?php

/**
 * @file
 * Code for the ADS Development.
 */

include_once 'ads_devel.features.inc';

define('MAX_SIZE_DEBUG', 100); // In MB.

/**
 * Implements hook_init().
 */
function ads_devel_init() {
  // Nothing here, just for code testing.
}

/**
 * Implements hook_form_alter().
 */
function ads_devel_form_alter(&$form, &$form_state, $form_id) {
  // var_dump($form_id, $form); exit;
}

/**
 * Implements hook_admin_paths_alter().
 */
function ads_devel_admin_paths_alter(&$paths) {
  // Return FALSE to the path where you don't want to show in OVERLAY
  // $paths['admin/*'] = FALSE; // This could break some stuff.
}

/**
 * Implements hook_watchdog().
 */
function ads_devel_watchdog($log_entry) {
  if ($log_entry['type'] == 'php' && $log_entry['severity'] <= WATCHDOG_WARNING) {
    // Devel: Log the backtrace into temporary file: drupal_debug.txt
    // Locate via: $ drush eval "echo file_directory_temp() . '/drupal_debug.txt'"
    function_exists('dd') && dd(debug_backtrace());
  }
}


/**
 * Implements hook_cron().
 */
function ads_devel_cron() {
  // Remove debug file if it's too big.
  $debug_file = file_directory_temp() . '/drupal_debug.txt';
  file_exists($debug_file) &&
    filesize($debug_file) > MAX_SIZE_DEBUG * pow(1024, 2) &&
      unlink($debug_file);
}

